### ISSUE TITLE
只添加一个cookie的时候会报列表索引超出范围的错误

### ISSUE THREAD

**Issue by Hyper-Beast** [AntonVanke/JDBrandMember#11]
如图，两个账号就正常了，目测两个或以上的账号数量没有这个问题

![image](https://user-images.githubusercontent.com/18001712/115896843-6a42b500-a48e-11eb-92a2-06de5454ae15.png)

**Comment by AntonVanke** [comment]
刚刚已经修复了，是因为我测试时一直使用的第二个号，你改成0就好了

**Comment by AntonVanke** [comment]
```json
{
    "thread": 6,
    "browserType": "Chrome",
    "headless": true,
    "binary": "",
    "useUser": 0,
    "users": []
}
```
其中`useUser`指的是使用第几个(按python下标计算)账号

**Comment by Hyper-Beast** [comment]
> 刚刚已经修复了，是因为我测试时一直使用的第二个号，你改成0就好了

OK,明白了。最早是以为可以一个结束了自动下一个，后面看了代码发现好像没做这个功能。测试了下比上个版本强太多了，上个版本开16线程直接卡死了，这个版本16个线程没问题了。

**Comment by AntonVanke** [comment]
上个版本的io操作太多了😂，这次把url.txt和shopid.txt合并了
