### ISSUE TITLE
反馈0.4颁布的2个exe会被360报毒隔离

### ISSUE THREAD

**Issue by bbilyvm** [AntonVanke/JDBrandMember#12]
如

**Comment by AntonVanke** [comment]
可能是由于`Pyinstaller`打包的原因
<https://habo.qq.com/file/showdetail?md5=a275afad21f52002164f112485b21917&pk=ADcGY11kB2IIO1s9U2c%3D>
<https://habo.qq.com/file/showdetail?md5=35813c994eac48ab1a0fbcaad4941083&pk=ADcGY11kB2IIO1s9U2A%3D>

**Comment by bbilyvm** [comment]
> 可能是由于`Pyinstaller`打包的原因
> https://habo.qq.com/file/showdetail?md5=a275afad21f52002164f112485b21917&pk=ADcGY11kB2IIO1s9U2c%3D
> https://habo.qq.com/file/showdetail?md5=35813c994eac48ab1a0fbcaad4941083&pk=ADcGY11kB2IIO1s9U2A%3D

再反馈一个，中途提示登录失败
[img]https://www.z4a.net/images/2021/04/27/20210427.png[/img]

**Comment by AntonVanke** [comment]
感谢反馈，可能是由于你网络环境的问题
