### ISSUE TITLE
我怀疑我在挖矿，建议加入记忆功能

### ISSUE THREAD

**Issue by uu5266** [AntonVanke/JDBrandMember#14]
网络，cpu高负荷，每次遍历都重新从头开始，能不能添加从上次失败处重新开始。

**Comment by AntonVanke** [comment]
好的，下次可能会加入
你如果觉得卡的话可以适当减少线程数

**Comment by uu5266** [comment]
上传几百KB，占用太高了吧，它在上传什么呢。

**Comment by AntonVanke** [comment]
京东页面的一些数据，你可以将headless改为false，thread改为1观看

**Comment by uu5266** [comment]
有些店铺没加入就跳到下一个店铺，是没奖励才跳过？遍历完所有店铺有多少京豆？运行一小时进度条还不到百分1，进度条靠谱吗？每次运行到接近百分之一时会出现“ERROR  登录失败  请使用‘add_cookie.py’添加cookie”，然后接着运行几分钟就退出，这是遍历完了吗？

**Comment by sola237** [comment]
开始了好久一直都是0京豆。。然后我就退出了 这样是正常的吗？

**Comment by AntonVanke** [comment]
有可能是你近期刷过了

**Comment by AntonVanke** [comment]
> 有些店铺没加入就跳到下一个店铺，是没奖励才跳过？遍历完所有店铺有多少京豆？运行一小时进度条还不到百分1，进度条靠谱吗？每次运行到接近百分之一时会出现“ERROR  登录失败  请使用‘add_cookie.py’添加cookie”，然后接着运行几分钟就退出，这是遍历完了吗？

没有，你的线程数太少了导致遍历速度过慢

**Comment by sola237** [comment]
![image](https://user-images.githubusercontent.com/63141812/116378503-c74eba00-a844-11eb-84cd-d8fb68b912d4.png)
大佬，我这样是正常的不，那么多带*号的是表示什么意思呢~不知道是入会成功了没有豆，还是入会失败了

**Comment by AntonVanke** [comment]
那个是我做的进度条哈哈哈，有点长了
