### ISSUE TITLE
下载win程序打开时直接闪退

### ISSUE THREAD

**Issue by 5wszxt** [AntonVanke/JDBrandMember#15]

**Comment by 5wszxt** [comment]
log里面都是浏览器驱动配置错误，但是已经下载了相匹配的谷歌和edge都试了，打开addcookie都是闪退，，，

**Comment by AntonVanke** [comment]
在文件夹下按住shift右键在powershell里运行看看报错什么

**Comment by w13689226302** [comment]
也是闪退   之前的就正常

**Comment by AntonVanke** [comment]
> 也是闪退 之前的就正常

检查一下浏览器版本号和驱动版本号是否对应？
或者在命令行内运行看一下报错是什么
