### ISSUE TITLE
目前发现的一些问题

### ISSUE THREAD

**Issue by AntonVanke** [AntonVanke/JDBrandMember#17]
1. 有时显示入会成功，但查询的时候却并没有入会成功
2. 显示的百分比忘记*100了
3. 在国外的服务器上运时会报登录失败的错误

**Comment by woboo110** [comment]
大佬，不搞个退会脚本吗

**Comment by AntonVanke** [comment]
> 大佬，不搞个退会脚本吗

😂没搞过，不知道怎么搞

**Comment by Hyper-Beast** [comment]
一个小建议，运行结束了不要自动退出，或者把这次运行获得多少写道日志里

**Comment by AntonVanke** [comment]
> 一个小建议，运行结束了不要自动退出，或者把这次运行获得多少写道日志里

好的

**Comment by lplbb** [comment]
> > 一个小建议，运行结束了不要自动退出，或者把这次运行获得多少写道日志里
> 
> 好的

z这个功能加上了吗

**Comment by AntonVanke** [comment]
> > > 一个小建议，运行结束了不要自动退出，或者把这次运行获得多少写道日志里
> > 
> > 好的
> 
> z这个功能加上了吗

是的，不过没有求和，请查看logs文件夹下的文件
