### ISSUE TITLE
macOS（inter及M1）均出现【浏览器错误 请检查你的驱动及配置】

### ISSUE THREAD

**Issue by zc-nju-med** [AntonVanke/JDBrandMember#18]
![photo_2021-04-29_23-13-46](https://user-images.githubusercontent.com/43012058/116574803-a7042580-a940-11eb-8750-6edcb90655d3.jpg)
如图所示。
分别在inter及M1苹果上测试Chrome和edge，均出现该报错；
切换到win10的edge，手动运行py脚本正常...

**Comment by AntonVanke** [comment]
我在MAC(intel)的Chrome运行是正常的，你可能是驱动的问题，你重新下载一下驱动试试

**Comment by zc-nju-med** [comment]
> 我在MAC(intel)的Chrome运行是正常的，你可能是驱动的问题，你重新下载一下驱动试试

<img width="242" alt="截屏2021-04-29 下午11 52 05" src="https://user-images.githubusercontent.com/43012058/116580584-1597b200-a946-11eb-9ab9-757b3af3f12c.png">
<img width="582" alt="截屏2021-04-29 下午11 51 50" src="https://user-images.githubusercontent.com/43012058/116580590-16c8df00-a946-11eb-903c-74c520d3e0e5.png">

这里是我的版本和我下载的驱动版本

重试之后依然是报错...

大佬你有电报群么？

**Comment by AntonVanke** [comment]
😂没有
![Screenshot_20210429_235917_com.github.android.jpg](https://user-images.githubusercontent.com/47097086/116581550-05cc9d80-a947-11eb-8ad9-99baeb88c5e5.jpg)
你要是用的是我刚更新的，你在main.py中把132行

```python
except WebDriverException:
        # 驱动问题
        print_log("ERROR", "浏览器错误", "请检查你的驱动和配置")
```

改为

```python

except WebDriverException:
        traceback.print_exc()
```

然后再次运行addcookie截图给我看看

**Comment by zc-nju-med** [comment]
> ```python
> except WebDriverException:
>         traceback.print_exc()
> ```

<img width="1375" alt="截屏2021-04-30 上午12 15 25" src="https://user-images.githubusercontent.com/43012058/116583686-331a4b00-a949-11eb-9443-568cbd630114.png">

这是新的错误内容
我的driver路径是有驱动的啊...

**Comment by AntonVanke** [comment]
应该是绝对路径的问题,把44行直接改成return file_name 吧![Screenshot_20210430_002149_com.github.android.jpg](https://user-images.githubusercontent.com/47097086/116585567-1e3eb700-a94b-11eb-9aa8-0e3a1cf3466f.jpg)

**Comment by AntonVanke** [comment]
https://npm.taobao.org/mirrors/chromedriver/90.0.4430.24/


你检查一下是从这下载的吗

**Comment by zc-nju-med** [comment]
> https://npm.taobao.org/mirrors/chromedriver/90.0.4430.24/
> 
> 你检查一下是从这下载的吗

谢谢大佬的耐心指导，我找驱动时直接翻到最后去了，没想到最前面就有，我下的是文档文件...
亲测M1 Mac也是可以正常运行的。
大佬可以修改一下readme了！

**Comment by AntonVanke** [comment]
> > https://npm.taobao.org/mirrors/chromedriver/90.0.4430.24/
> > 你检查一下是从这下载的吗
> 
> 谢谢大佬的耐心指导，我找驱动时直接翻到最后去了，没想到最前面就有，我下的是文档文件...
> 亲测M1 Mac也是可以正常运行的。
> 大佬可以修改一下readme了！

好的，感谢你的测试。
另外，你通过这个刷了多少个豆啊，我感觉我刷的豆好少啊

**Comment by zc-nju-med** [comment]
> > > https://npm.taobao.org/mirrors/chromedriver/90.0.4430.24/
> > > 你检查一下是从这下载的吗
> > 
> > 
> > 谢谢大佬的耐心指导，我找驱动时直接翻到最后去了，没想到最前面就有，我下的是文档文件...
> > 亲测M1 Mac也是可以正常运行的。
> > 大佬可以修改一下readme了！
> 
> 好的，感谢你的测试。
> 另外，你通过这个刷了多少个豆啊，我感觉我刷的豆好少啊

昨天用win测试一次
刚刚用M1测试了一次
一共大概1300豆左右吧 粗略估算
