### ISSUE TITLE
win版本log提示 ERROR  浏览器错误  请检查你的驱动和配置

### ISSUE THREAD

**Issue by lamelin** [AntonVanke/JDBrandMember#19]
浏览器版本跟drivers都对上了，运行add_cookie还是提示错误
![1](https://user-images.githubusercontent.com/80474492/116600410-dd9b6980-a95b-11eb-8427-f5e9431d2c90.jpg)
![2](https://user-images.githubusercontent.com/80474492/116600694-294e1300-a95c-11eb-9218-f949f2a04849.jpg)

**Comment by AntonVanke** [comment]
找不到Chrome浏览器
解决办法
浏览器输入chrome://version命令
找到命令行中的可执行文件路径，加入到config的binary中:
例如:
"binary": "C:/CHROME/chrome.exe"

**Comment by lamelin** [comment]
> 找不到Chrome浏览器
> 解决办法
> 浏览器输入chrome://version命令
> 找到命令行中的可执行文件路径，加入到config的binary中:
> **例如**:
> "binary": "C:/CHROME/chrome.exe"
> 或添加C:/CHROME/到环境变量中

按照您的方法，还是不行
![1619744159(1)](https://user-images.githubusercontent.com/80474492/116635910-911f5080-a992-11eb-8e9a-9328e4208d4a.jpg)

**Comment by AntonVanke** [comment]
你是不是打成\线了，要打成这个/才行，或者\\
例如

```json
    {"binary": "C:/Library/Developer/CommandLineTools/"}
```

```json
    {"binary": "C:\\Library\\Developer\\CommandLineTools\\"}
```

**Comment by lamelin** [comment]
> 你是不是打成`\`线了，要打成这个`/`才行，或者`\\`
> 例如
> 
> ```json
>     {"binary": "C:/Library/Developer/CommandLineTools/"}
> ```
> 
> ```json
>     {"binary": "C:\\Library\\Developer\\CommandLineTools\\"}
> ```

没错的，我是直接复制进去的
![image](https://user-images.githubusercontent.com/80474492/116639228-97192f80-a99a-11eb-84db-8d83bead3c8a.png)

**Comment by AntonVanke** [comment]
把反斜线修改为斜线即可

**Comment by youngda** [comment]
很奇怪，是相同的错误，不过试了5天前发布的打包好的可以运行。
{
    "thread": 6,
    "browserType": "Chrome",
    "headless": true,
    "binary": "C:\\Program Files\\Google\\Chrome\\Application\\",
    "useUser": 0,
    "users": []
}

**Comment by youngda** [comment]
是两条\，github 提交后变一条了
`{
    "thread": 6,
    "browserType": "Chrome",
    "headless": true,
    "binary": "C:\\Program Files\\Google\\Chrome\\Application\\",
    "useUser": 0,
    "users": []
}`

**Comment by AntonVanke** [comment]
> 很奇怪，是相同的错误，不过试了5天前发布的打包好的可以运行。
> {
>     "thread": 6,
>     "browserType": "Chrome",
>     "headless": true,
>     "binary": "C:\\Program Files\\Google\\Chrome\\Application\\",
>     "useUser": 0,
>     "users": []
> }

```python
{
    "thread": 6,
    "browserType": "Chrome",
    "headless": true,
    "binary": "C:/Program Files/Google/Chrome/Application/chrome.exe",
    "useUser": 0,
    "users": []
}
```

**Comment by youngda** [comment]
谢谢，试了，也是不行，为啥发行版可以正常运行，好奇怪。

**Comment by AntonVanke** [comment]
> > 很奇怪，是相同的错误，不过试了5天前发布的打包好的可以运行。
> > {
> >     "thread": 6,
> >     "browserType": "Chrome",
> >     "headless": true,
> >     "binary": "C:\\Program Files\\Google\\Chrome\\Application\\",
> >     "useUser": 0,
> >     "users": []
> > }
> 
> ```python
> {
>     "thread": 6,
>     "browserType": "Chrome",
>     "headless": true,
>     "binary": "C:/Program Files/Google/Chrome/Application/chrome.exe",
>     "useUser": 0,
>     "users": []
> }
> ```

    玄学😂，有可能是pyinstaller的功劳

**Comment by AntonVanke** [comment]
> 谢谢，试了，也是不行，为啥发行版可以正常运行，好奇怪。

玄学😂，有可能是pyinstaller的功劳

**Comment by youngda** [comment]
大佬幸苦了，发行版可用，期待发布发行版更新

**Comment by lamelin** [comment]
> 把反斜线修改为斜线即可

改完之后运行，还是出现之前的情况，浏览器驱动跟浏览器版本是对的上的
![image](https://user-images.githubusercontent.com/80474492/116645309-20832e80-a9a8-11eb-9a05-0798d6d34316.png)
![image](https://user-images.githubusercontent.com/80474492/116645340-35f85880-a9a8-11eb-96ec-6f17d9c0d470.png)

**Comment by AntonVanke** [comment]
> > 把反斜线修改为斜线即可
> 
> 改完之后运行，还是出现之前的情况，浏览器驱动跟浏览器版本是对的上的
> ![image](https://user-images.githubusercontent.com/80474492/116645309-20832e80-a9a8-11eb-9a05-0798d6d34316.png)
> ![image](https://user-images.githubusercontent.com/80474492/116645340-35f85880-a9a8-11eb-96ec-6f17d9c0d470.png)
> 

我等会回去解决一下，好奇怪啊

**Comment by jiurou** [comment]
吐了，折腾一晚，各种换杠杠，也添加环境变量，log里一直都是“ERROR  浏览器错误  请检查你的驱动和配置”
我一个编程盲光是装那三个安装包就够喝一壶了，
结果临门一脚还是给踹出去了😂😂😂
添加cookie这一步挡住我了

**Comment by jiurou** [comment]
作为编程盲，好不容易一边吐血一边装好那三个包，结果我也出现了一样的问题浏览器配置错误，继续一边吐血一边搞了好久
猛然发现，我下载错浏览器驱动了，项目主提供的页面有两种链接，点击LATEST_RELEASE开头的链接获得的是空白文件，这是错的。要点击数字开头的链接，比如我的是版本是90.0.4430.24/
进去里面根据系统下载后解压放到该放的位置，
成功读条

**Comment by lamelin** [comment]
驱动跟浏览器版本都没问题，还是提示一样的错误，唉~~都不知道哪里出了问题

**Comment by AntonVanke** [comment]
> 驱动跟浏览器版本都没问题，还是提示一样的错误，唉~~都不知道哪里出了问题

有错误截图吗

**Comment by AntonVanke** [comment]
> 作为编程盲，好不容易一边吐血一边装好那三个包，结果我也出现了一样的问题浏览器配置错误，继续一边吐血一边搞了好久
> 猛然发现，我下载错浏览器驱动了，项目主提供的页面有两种链接，点击LATEST_RELEASE开头的链接获得的是空白文件，这是错的。要点击数字开头的链接，比如我的是版本是90.0.4430.24/
> 进去里面根据系统下载后解压放到该放的位置，
> 成功读条

你刷了多少呢，我感觉京豆越来越难刷了，连每天的运动京豆也从100降到了30

**Comment by jiurou** [comment]
> > 作为编程盲，好不容易一边吐血一边装好那三个包，结果我也出现了一样的问题浏览器配置错误，继续一边吐血一边搞了好久
> > 猛然发现，我下载错浏览器驱动了，项目主提供的页面有两种链接，点击LATEST_RELEASE开头的链接获得的是空白文件，这是错的。要点击数字开头的链接，比如我的是版本是90.0.4430.24/
> > 进去里面根据系统下载后解压放到该放的位置，
> > 成功读条
> 
> 你刷了多少呢，我感觉京豆越来越难刷了，连每天的运动京豆也从100降到了30

我就刚才回复后开始的，总共600个的样子吧，我在看电影，中途有两次自动退出了，

**Comment by lamelin** [comment]
自动入会那个脚本，我研究了几天，还是找不到问题所在，换了部电脑还是一样问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月5日(星期三) 晚上11:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AntonVanke/JDBrandMember] win版本log提示 ERROR  浏览器错误  请检查你的驱动和配置 (#19)





   
作为编程盲，好不容易一边吐血一边装好那三个包，结果我也出现了一样的问题浏览器配置错误，继续一边吐血一边搞了好久
 猛然发现，我下载错浏览器驱动了，项目主提供的页面有两种链接，点击LATEST_RELEASE开头的链接获得的是空白文件，这是错的。要点击数字开头的链接，比如我的是版本是90.0.4430.24/
 进去里面根据系统下载后解压放到该放的位置，
 成功读条
  
你刷了多少呢，我感觉京豆越来越难刷了，连每天的运动京豆也从100降到了30
  
我就刚才回复后开始的，总共600个的样子吧，我在看电影，中途有两次自动退出了，
 
&mdash;

**Comment by AntonVanke** [comment]
> 自动入会那个脚本，我研究了几天，还是找不到问题所在，换了部电脑还是一样问题
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年5月5日(星期三) 晚上11:23 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [AntonVanke/JDBrandMember] win版本log提示 ERROR 浏览器错误 请检查你的驱动和配置 (#19) 作为编程盲，好不容易一边吐血一边装好那三个包，结果我也出现了一样的问题浏览器配置错误，继续一边吐血一边搞了好久 猛然发现，我下载错浏览器驱动了，项目主提供的页面有两种链接，点击LATEST_RELEASE开头的链接获得的是空白文件，这是错的。要点击数字开头的链接，比如我的是版本是90.0.4430.24/ 进去里面根据系统下载后解压放到该放的位置， 成功读条 你刷了多少呢，我感觉京豆越来越难刷了，连每天的运动京豆也从100降到了30 我就刚才回复后开始的，总共600个的样子吧，我在看电影，中途有两次自动退出了， &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

驱动问题的话，下载驱动时不要下载`LATEST_RELEASE`的而应该是版本号文件夹

**Comment by lamelin** [comment]
肯定不是下载你说的那个，今天我回公司找了部电脑试了下，没问题。就家里的两部电脑不行，我怀疑跟cpu有关



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月6日(星期四) 下午3:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AntonVanke/JDBrandMember] win版本log提示 ERROR  浏览器错误  请检查你的驱动和配置 (#19)





  
自动入会那个脚本，我研究了几天，还是找不到问题所在，换了部电脑还是一样问题
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年5月5日(星期三) 晚上11:23 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [AntonVanke/JDBrandMember] win版本log提示 ERROR 浏览器错误 请检查你的驱动和配置 (#19) 作为编程盲，好不容易一边吐血一边装好那三个包，结果我也出现了一样的问题浏览器配置错误，继续一边吐血一边搞了好久 猛然发现，我下载错浏览器驱动了，项目主提供的页面有两种链接，点击LATEST_RELEASE开头的链接获得的是空白文件，这是错的。要点击数字开头的链接，比如我的是版本是90.0.4430.24/ 进去里面根据系统下载后解压放到该放的位置， 成功读条 你刷了多少呢，我感觉京豆越来越难刷了，连每天的运动京豆也从100降到了30 我就刚才回复后开始的，总共600个的样子吧，我在看电影，中途有两次自动退出了， — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
驱动问题的话，下载驱动时不要下载LATEST_RELEASE的而应该是版本号文件夹

**Comment by mrwangsg** [comment]
![image](https://user-images.githubusercontent.com/15097460/131215127-09a55876-ede3-4f66-b8d0-2e733e88f8e4.png)

我这个跑完之后，好像没有京豆值变化的。正常嘛？
