### ISSUE TITLE
运行一会儿后面全部都是访问error的页面

### ISSUE THREAD

**Issue by Hyper-Beast** [AntonVanke/JDBrandMember#2]
请问这个是短时内访问太多次京东被京东暂时屏蔽了吗？

**Comment by AntonVanke** [comment]
由于京东的有些店铺没有开通店铺会员，所以会有错误页面，并不会影响实际功能。
我正在遍历这50万个店铺中有店铺会员的店铺id，遍历完成后应该不会再有未找到的页面。
而且遍历的效率会大幅度提升
