### ISSUE TITLE
配置多账户，但是只跑了第一个账户

### ISSUE THREAD

**Issue by wingsstudio** [AntonVanke/JDBrandMember#20]
如题，已添加多账户，不过`pyhont3 main.py`后只跑了第一个账户

**Comment by AntonVanke** [comment]
抱歉，我暂时还没有添加多账号同时刷功能，现在需要你手动更改`use_user`，下个版本会有的

**Comment by wingsstudio** [comment]
可否配置use_user为0,1,2,3这样进行依次刷？

**Comment by wingsstudio** [comment]
> 抱歉，我暂时还没有添加多账号同时刷功能，现在需要你手动更改`use_user`，下个版本会有的

这几天跑下来发现cookie的有效期有点短，想手动替换发现config里面只有pt_pin没有pt_key，可否考虑支持手动填写cookie

**Comment by Hyper-Beast** [comment]
> > > 抱歉，我暂时还没有添加多账号同时刷功能，现在需要你手动更改`use_user`，下个版本会有的
> > 
> > 
> > 这几天跑下来发现cookie的有效期有点短，想手动替换发现config里面只有pt_pin没有pt_key，可否考虑支持手动填写cookie
> 
> 额，突然发现这还有个问题。
> 你说的`pt_pin`和`pt_key`是手机端的，有效期会长一些，而在电脑端`cookie`有效期很短的

ptkey ptpin可以直接从jd_scripts哪里拿过来，如果可以确实方便很多

**Comment by AntonVanke** [comment]
> > > > 抱歉，我暂时还没有添加多账号同时刷功能，现在需要你手动更改`use_user`，下个版本会有的
> > > 
> > > 
> > > 这几天跑下来发现cookie的有效期有点短，想手动替换发现config里面只有pt_pin没有pt_key，可否考虑支持手动填写cookie
> > 
> > 额，突然发现这还有个问题。
> > 你说的`pt_pin`和`pt_key`是手机端的，有效期会长一些，而在电脑端`cookie`有效期很短的
> 
> ptkey ptpin可以直接从jd_scripts哪里拿过来，如果可以确实方便很多

我会研究研究的
