### ISSUE TITLE
有个小问题

### ISSUE THREAD

**Issue by mohui2019** [AntonVanke/JDBrandMember#22]
用外国号注册的我的小号，程序显示入会成功并有豆入，但账号上没有豆增加，应该入会不成功，国内号码正常

**Comment by AntonVanke** [comment]
我也注意到这个问题了
加一个验证可以确认是否获得成功，但刷豆速度可能会下降

**Comment by AntonVanke** [comment]
> 用外国号注册的我的小号，程序显示入会成功并有豆入，但账号上没有豆增加，应该入会不成功，国内号码正常

有可能是国外需要额外的收一个手机验证码(猜测)

**Comment by mohui2019** [comment]
外国手机号在京东上显示根本不对，比如香港号+（852）52358733，京东显示852-52358733，正常显示+85252358733。
如果自动入会也能自动退会就好了，不然这个号码基本就废了，上万个店铺每天都给会员号码发一条促销短信，手机基上本爆了

**Comment by AntonVanke** [comment]
退会需要接手机验证码还有验证码，要是有在网页端退会的方法就好了
