### ISSUE TITLE
两个功能应该加一下

### ISSUE THREAD

**Issue by underlaw** [AntonVanke/JDBrandMember#23]
1、是记忆功能，也就是上次跑到哪了，可提示是从头跑起还是接上次；
2、入会条件选择，比如小于多少京豆的就不加入

退出时，大量浏览器进程未退出

**Comment by AntonVanke** [comment]
- [x] 退出时，大量浏览器进程未退出
- [x] 入会条件选择，比如小于多少京豆的就不加入
- [ ] 是记忆功能，也就是上次跑到哪了，可提示是从头跑起还是接上次；
