### ISSUE TITLE
开启获取红包的参数是true吗，好像没有效果

### ISSUE THREAD

**Issue by Hyper-Beast** [AntonVanke/JDBrandMember#24]
{
    "thread": 16,
    "binary": "",
    "headless": true,
    "useUser": 0,
    "threshold": 0,
    "is_get_voucher": true,
    "users": []
}

**Comment by AntonVanke** [comment]
是的
```python
{
    "thread": 6,
    "binary": "",
    "headless": true,
    "useUser": 0,
    "threshold": 0,
    "is_get_voucher": true,
    "users": []
}
```

如果没有效果，可能是送红包的店铺比较少，或者是你都入会过了，我昨天也才跑了20元的红包

**Comment by AntonVanke** [comment]
> {
> "thread": 16,
> "binary": "",
> "headless": true,
> "useUser": 0,
> "threshold": 0,
> "is_get_voucher": true,
> "users": []
> }

刚刚突然发现原来是参数错了，我说我怎么也刷不到红包了
