### ISSUE TITLE
又来提建议了

### ISSUE THREAD

**Issue by underlaw** [AntonVanke/JDBrandMember#25]
首先感谢作者增加的1、入会条件 2、退出时进程的改进。

又有点想法了，如下：
1、增加已入会店铺签到功能（ 获取积分或京豆）；
2、增加参加店铺活动功能（如有抽奖）；
3、增加多账号选择运行功能。

以上纯个建议，觉得如果光跑一个入会，这软件就会成为一次性软件了，因为退会麻烦。增加以上功能可能给本软件带来长久使用。

**Comment by AntonVanke** [comment]
**感谢你的建议**

对于`3、增加多账号选择运行功能。`，其实是有的
在`config.json`中: 
```python
{...
"useUser": 0,  # 使用的用户: 0 表示所有、1 代表第 1 个，以此类推
...}
```

`useUser`可以选择用户，0代表执行所有账户，1代表只执行第一个账户，填写n就代表执行第n个账号

---

例如我`    "useUser": 2,`则在运行时可以看到第二个被选中
[![运行截图](https://z3.ax1x.com/2021/05/15/gyXpxU.png)](https://imgtu.com/i/gyXpxU)

---

对于`1、增加已入会店铺签到功能（ 获取积分或京豆）；2、增加参加店铺活动功能（如有抽奖）；`这些操作可以在网页端完成吗？由于我是用的`selenium`模拟操作网页，所以只能执行在网页上执行的动作

这个脚本我认为是一次性的，因为现在京东的脚本已经很多了，像我室友就使用`京东助手--by 小赤佬`，那上面有很多脚本，我也是看到上面没有遍历店铺的脚本才写的这个，其它的上面都有。

---

如果你找到`1、 2、`京东网址也可以发给我，我会添加的，再次感谢

**Comment by underlaw** [comment]
> 铺的脚本才写的这个，其它的上面都有。

感谢回复
