### ISSUE TITLE
大佬这个是什么问题

### ISSUE THREAD

**Issue by kaikii98** [AntonVanke/JDBrandMember#26]
File "main.py", line 380
    shopID: list = open(get_file_path("shopid.txt"), "r").readlines()
    ^
SyntaxError: annotated name 'shopID' can't be global

**Comment by AntonVanke** [comment]
> File "main.py", line 380
> shopID: list = open(get_file_path("shopid.txt"), "r").readlines()
> ^
> SyntaxError: annotated name 'shopID' can't be global

是否使用的是`python 3.7 及以下`?建议升级python版本尝试

Issue #1
