### ISSUE TITLE
feat: 希望可以支持直接调用入口

### ISSUE THREAD

**Issue by lihuacai168** [AntonVanke/JDBrandMember#27]
- 目前是需要python main.py这样允许，然后选择运行。配置成定时任务来跑的话，没有入口。
- 另外，线程数的配置希望可以给一个参考的建议，比如4c 8g可以配置多少个线程
- 脚本是每天跑都有收益吗？还是需要间隔多长时间呢~希望可以给出一个参考的建议。

**Comment by AntonVanke** [comment]
> * 目前是需要python main.py这样允许，然后选择运行。配置成定时任务来跑的话，没有入口。
> * 另外，线程数的配置希望可以给一个参考的建议，比如4c 8g可以配置多少个线程
> * 脚本是每天跑都有收益吗？还是需要间隔多长时间呢~希望可以给出一个参考的建议。

1. 好的
2. 我一般设置的线程数是`1*c-2*c`之间，`每个线程会占用256M的内存`
3. 我并没有经常去跑，一般是15天跑一次，因为入会有礼的活动店铺并不是很多，经常跑的话收益率低
