### ISSUE TITLE
领完了快速刷的就没有了

### ISSUE THREAD

**Issue by hexiaoshi2019** [AntonVanke/JDBrandMember#3]
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/54265674/114551854-84aeae80-9c96-11eb-8d8b-2a7426baf671.png">
下面的就就一直没有
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/54265674/114551950-a019b980-9c96-11eb-8767-16cd67c6cff5.png">
麻烦看看谢谢

**Comment by Hyper-Beast** [comment]
不是没有，你多等等就有了，不过很少了。这个是从0开始一个个访问效率很低，很多页面都是不存在的。

**Comment by hexiaoshi2019** [comment]
大佬：有些入会，会员里面积分是可以兑换京豆，能否加个这样的功能呀？

**Comment by AntonVanke** [comment]
我将没有开通店铺会员的店铺 id 都剔除了，现在可以在 30 分钟内遍历一遍店铺，而且你每隔几天就可以再遍历一次。我 
 14 天前遍历过一遍，今天早上又遍历时还可以增加 2600 京豆。
至于那个会员积分兑换京豆的，我找了好多店铺都没看见有

**Comment by hexiaoshi2019** [comment]
我是看到有些有，改天截图给你，这个项目能否使用docker来跑。这样遍历就方便了。

**Comment by AntonVanke** [comment]
好的，感谢

**Comment by CalmLong** [comment]
这个会有副作用吗

**Comment by AntonVanke** [comment]
> 这个会有副作用吗

暂时没有发现
