### ISSUE TITLE
报错 大佬看一下什么问题

### ISSUE THREAD

**Issue by geeklx** [AntonVanke/JDBrandMember#31]
shopID: list = open(get_file_path("shopid.txt"), "r").readlines()
    ^
SyntaxError: annotated name 'shopID' can't be global

**Comment by AntonVanke** [comment]
> ```
> shopID: list = open(get_file_path("shopid.txt"), "r").readlines()
> ^
> ```
> 
> SyntaxError: annotated name 'shopID' can't be global

是否使用的是python 3.7 及以下?建议升级python版本尝试

Issue #1

**Comment by geeklx** [comment]
就是3.7
