### ISSUE TITLE
当从店铺退会后重新入会还能有机会得到奖励吗

### ISSUE THREAD

**Issue by yemingjkl** [AntonVanke/JDBrandMember#32]
还是即使不用退会员也隔半个月仍然获得京豆，或者说一个店铺只有一次获得京豆的机会，无论后续退会员与否？

**Comment by AntonVanke** [comment]
`一个店铺只有一次获得京豆的机会，无论后续退会员与否`。
因为店铺的基数比较多，所以并不需要退会,隔一段时间后会有其他店铺有入会有礼

> 还是即使不用退会员也隔半个月仍然获得京豆，或者说一个店铺只有一次获得京豆的机会，无论后续退会员与否？
