### ISSUE TITLE
问个问题，关于多账号的。

### ISSUE THREAD

**Issue by ryan016** [AntonVanke/JDBrandMember#34]
win版，这个程序在开始执行时，是一个账号一个账号逐个去跑的吗？而不是多个账号同时执行？

![11111](https://user-images.githubusercontent.com/26700603/118906018-761b7d00-b94f-11eb-9145-72875fa62960.png)

**Comment by AntonVanke** [comment]
> win版，这个程序在开始执行时，是一个账号一个账号逐个去跑的吗？而不是多个账号同时执行？
> 
> ![11111](https://user-images.githubusercontent.com/26700603/118906018-761b7d00-b94f-11eb-9145-72875fa62960.png)

并不是多账号一起跑，而是一个账号先执行，执行的结果用于其他账号。
因为在短期时间内，执行的结果（活动店铺）不变。

**Comment by ryan016** [comment]
> > win版，这个程序在开始执行时，是一个账号一个账号逐个去跑的吗？而不是多个账号同时执行？
> > ![11111](https://user-images.githubusercontent.com/26700603/118906018-761b7d00-b94f-11eb-9145-72875fa62960.png)
> 
> 并不是多账号一起跑，而是一个账号先执行，执行的结果用于其他账号。
> 因为在短期时间内，执行的结果（活动店铺）不变。

这样时间上是不是能缩短？

**Comment by AntonVanke** [comment]
> > > win版，这个程序在开始执行时，是一个账号一个账号逐个去跑的吗？而不是多个账号同时执行？
> > > ![11111](https://user-images.githubusercontent.com/26700603/118906018-761b7d00-b94f-11eb-9145-72875fa62960.png)
> > 
> > 
> > 并不是多账号一起跑，而是一个账号先执行，执行的结果用于其他账号。
> > 因为在短期时间内，执行的结果（活动店铺）不变。
> 
> 这样时间上是不是能缩短？

是的，比一个一个跑要快很多

**Comment by ryan016** [comment]
好的，谢谢！！！
