### ISSUE TITLE
有进度，但是不出豆

### ISSUE THREAD

**Issue by crane168** [AntonVanke/JDBrandMember#36]
账号也添加了，有进度，但是没有豆入账，这是是什么情况啊
![image](https://user-images.githubusercontent.com/26795319/119085898-2c0dc680-ba37-11eb-9c32-d36b17479de5.png)

**Comment by AntonVanke** [comment]
> 账号也添加了，有进度，但是没有豆入账，这是是什么情况啊
> ![image](https://user-images.githubusercontent.com/26795319/119085898-2c0dc680-ba37-11eb-9c32-d36b17479de5.png)
> 

跑完了也没有豆吗?日志显示什么，配置的是几线程?

**Comment by crane168** [comment]
![image](https://user-images.githubusercontent.com/26795319/119098885-ece87100-ba48-11eb-8d05-1ccd524b4655.png)
一直在跑，线程是默认的6线程，依旧没有豆增加

**Comment by AntonVanke** [comment]
可能有两个原因：
1. 你最近有过用类似的脚本，或者手动入会完了
2. 可能你的号是个黑号，入会是不能得到奖励的，所以没有可以入会的店铺

**Comment by crane168** [comment]
> 可能有两个原因：
> 
> 1. 你最近有过用类似的脚本，或者手动入会完了
> 2. 可能你的号是个黑号，入会是不能得到奖励的，所以没有可以入会的店铺
估计真黑了

**Comment by AntonVanke** [comment]
> > 可能有两个原因：
> > 
> > 1. 你最近有过用类似的脚本，或者手动入会完了
> > 2. 可能你的号是个黑号，入会是不能得到奖励的，所以没有可以入会的店铺
> 估计真黑了
> 

这个账号，这是第一次用这个脚本刷吗

**Comment by lanyucomputer** [comment]
验证账号1中，中途退出可能会误认为账号失效而删除

--------------------
如果需要退出，请 ctrl + c 输入 3 退出，否则可能本次运行的结果不会保存
--------------------
用户列表    用户名                 京豆数量      是否在执行列表
1         jd_18888888888888       3944          1
选择
        1. 开始执行
        2. 添加账号
        3. 退出
        >  1
当前账号：jd_18888888888888
正在执行：0.48925%[->****************************************]状态：在10215768号店铺获得2京豆豆
--------------------
如果需要退出，请 ctrl + c 输入 3 退出，否则可能本次运行的结果不会保存
--------------------
用户列表    用户名                 京豆数量      是否在执行列表
1          jd_18888888888888      3944          1
选择
        1. 开始执行
        2. 添加账号
        3. 退出
        >  3
日志已生成，查看./logs/ Some log data is being generated: ./log/ ...正在关闭，不要退出
