### ISSUE TITLE
服务器使用chrome的driver出现crash

### ISSUE THREAD

**Issue by feishi12121** [AntonVanke/JDBrandMember#4]
![Snipaste_2021-04-17_23-16-12](https://user-images.githubusercontent.com/31927191/115117949-944e3000-9fd3-11eb-9cf1-9f7c7badda6b.png)

**Comment by AntonVanke** [comment]
或许你可以参考这篇文章<https://blog.csdn.net/blueheart20/article/details/81566903>
如果错误仍未解决请告诉我
