### ISSUE TITLE
退会及TG电报群的一些问题

### ISSUE THREAD

**Issue by fruitbook** [AntonVanke/JDBrandMember#42]

**Comment by AntonVanke** [comment]
我会在后续研究批量退会（销卡）的方法的

---

但

1. 不是所有店铺都可以退会
2. 批量退会可能会造成黑号

**Comment by fruitbook** [comment]
> 退会需要手机验证码
> 
> 且
> 
> 1. 不是所有店铺都可以退会
> 2. 批量退会可能会造成黑号

那能增加个ck登录吗 我下载的是直接那个exe的 添加一个账号进去 没法选择执行哪个啊

**Comment by AntonVanke** [comment]
> > 退会需要手机验证码
> > 且
> > 
> > 1. 不是所有店铺都可以退会
> > 2. 批量退会可能会造成黑号
> 
> 那能增加个ck登录吗 我下载的是直接那个exe的 添加一个账号进去 没法选择执行哪个啊

我正在测试 V0.6 版本的马上就会有 CK 版本的了

**Comment by fruitbook** [comment]
> > > 退会需要手机验证码
> > > 且
> > > 
> > > 1. 不是所有店铺都可以退会
> > > 2. 批量退会可能会造成黑号
> > 
> > 
> > 那能增加个ck登录吗 我下载的是直接那个exe的 添加一个账号进去 没法选择执行哪个啊
> 
> 我正在测试 V0.6 版本的马上就会有 CK 版本的了

大佬有交流群吗

**Comment by AntonVanke** [comment]
> > > > 退会需要手机验证码
> > > > 且
> > > > 
> > > > 1. 不是所有店铺都可以退会
> > > > 2. 批量退会可能会造成黑号
> > > 
> > > 
> > > 那能增加个ck登录吗 我下载的是直接那个exe的 添加一个账号进去 没法选择执行哪个啊
> > 
> > 我正在测试 V0.6 版本的马上就会有 CK 版本的了
> 
> 大佬有交流群吗 

没有😂

**Comment by fruitbook** [comment]
> > > > > 退会需要手机验证码
> > > > > 且
> > > > > 
> > > > > 1. 不是所有店铺都可以退会
> > > > > 2. 批量退会可能会造成黑号
> > > > 
> > > > 
> > > > 那能增加个ck登录吗 我下载的是直接那个exe的 添加一个账号进去 没法选择执行哪个啊
> > > 
> > > 
> > > 我正在测试 V0.6 版本的马上就会有 CK 版本的了
> > 
> > 
> > 大佬有交流群吗
> 
> 没有😂

要不弄个交流群吧 tg qq都行 顺便问一下什么时候更新新版本啊

**Comment by Xzw111222** [comment]
没填手机号也会给你发短信吗

**Comment by AntonVanke** [comment]
> 没填手机号也会给你发短信吗

用你京东注册的qq号的

**Comment by AntonVanke** [comment]
> > > > > > 退会需要手机验证码
> > > > > > 且
> > > > > > 
> > > > > > 1. 不是所有店铺都可以退会
> > > > > > 2. 批量退会可能会造成黑号
> > > > > 
> > > > > 
> > > > > 那能增加个ck登录吗 我下载的是直接那个exe的 添加一个账号进去 没法选择执行哪个啊
> > > > 
> > > > 
> > > > 我正在测试 V0.6 版本的马上就会有 CK 版本的了
> > > 
> > > 
> > > 大佬有交流群吗
> > 
> > 
> > 没有😂
> 
> 要不弄个交流群吧 tg qq都行 顺便问一下什么时候更新新版本啊

感觉没有必要，不过你知道什么京东tg群吗，好想学习一下😂

**Comment by AntonVanke** [comment]
退会的那个`?venderId=`真的把我坑惨了，原来在api中是`brandId`😓

**Comment by AntonVanke** [comment]
退会已经有了@yqchilde大佬的[JDMemberCloseAccount](https://github.com/yqchilde/JDMemberCloseAccount/),另外他也建立了`tg`群[https://t.me/joinchat/KhS18aPM9I9jZWVl](https://t.me/joinchat/KhS18aPM9I9jZWVl)可以去试试
