### ISSUE TITLE
一个提醒和一个问题

### ISSUE THREAD

**Issue by Hyper-Beast** [AntonVanke/JDBrandMember#43]
提醒：如何获取cookie的说明里你忘记把自己的号码打码了
问题：
# 用户注册时所填写的信息
register:
  v_sex: 男  # 要求: 男 or 女
  v_birthday: 2000-09-27  # 要求: yyyy-mm-dd
  v_name: 康有为  # 要求: 1 - 10 个字符

我如果有多个pt_key pt_pin这个怎么搞，也多个吗，还是都用同一个

**Comment by AntonVanke** [comment]
哈哈，感谢，那个并不是我的真实信息

---

多个`cookie`共用一个`register`信息，并不会有什么冲突
