### ISSUE TITLE
新版本点那个main.exe闪退啊

### ISSUE THREAD

**Issue by fruitbook** [AntonVanke/JDBrandMember#46]
win10系统

**Comment by AntonVanke** [comment]
log输出什么

**Comment by abc79461352** [comment]
同样问题 log输出
2021-05-31 17:50:13  INFO  执行结束
我在想是不是WINDOWS的放错文件了 放了MAC的文件  和原来的文件不同了 没有驱动文件夹了

**Comment by AntonVanke** [comment]
我已经将驱动去掉了，这个问题可能是`yaml`文件编码问题， 可以下载新的打包尝试一下

https://github.com/AntonVanke/JDBrandMember/releases

**Comment by AntonVanke** [comment]
是否已解决问题？

**Comment by abc79461352** [comment]
已经解决问题,大佬威武!

**Comment by ryan016** [comment]
原来是代码写错了  问题解决
