### ISSUE TITLE
No module named 'yaml',提示找不到这个模块

### ISSUE THREAD

**Issue by crane168** [AntonVanke/JDBrandMember#55]
![image](https://user-images.githubusercontent.com/26795319/121464566-ac946700-c9e6-11eb-9071-9567305a472c.png)
看了已经安装了，不知道什么情况

**Comment by AntonVanke** [comment]
使用`pip3 install -r requirements.txt`安装后再次执行`python3 main.py`

**Comment by crane168** [comment]
> 使用`pip3 install -r requirements.txt`安装后再次执行`python3 main.py`

厉害了  大佬  好使
