### ISSUE TITLE
运行后出现乱码

### ISSUE THREAD

**Issue by zglzw** [AntonVanke/JDBrandMember#7]
扫码登录一段时间后，google chrome自动关闭，cmd出现乱码，cpu占用率达到了100%，请问是怎么回事？
![捕获](https://user-images.githubusercontent.com/27610233/115197172-46e0d880-a123-11eb-8c47-0d0bc71e2fbb.PNG)

**Comment by AntonVanke** [comment]
你这是快速刷分完毕后，进入遍历刷分了，遍历刷分用的是无头模式，所以你看到浏览器会退出。而且由于遍历用了多个线程所以占用率会上升。
至于乱码则是`chromewebdrive`输出的警告，命令提示符的原因造成乱码，你可以忽略这些信息。
遍历会刷完所有的京东店铺，但由于你快速刷分已经刷完了近期的送京豆店铺，所以回报率会很低。如果你觉得卡顿的话，可以跳过这一部分

**Comment by zglzw** [comment]
好的明白了，谢谢大佬
