### ISSUE TITLE
是否考虑快速刷豆也加入多线程

### ISSUE THREAD

**Issue by Hyper-Beast** [AntonVanke/JDBrandMember#9]
如果也加入了进一步增加效率

**Comment by hexiaoshi2019** [comment]
加多线程。怕封号嗯。

**Comment by AntonVanke** [comment]
好的，我在本地电脑上已经试验了快速刷分的多线程。
至于号被拉入黑名单，暂时还没有发生。我在服务器上跑30线程的，没有被封过。
主要是selenium太麻烦了还需要配置驱动，我准备学一下puppeteer，这样还可以在actions上挂着跑
